---
invoiceninja_version: "5.13.43"
invoiceninja_dir: "/opt/invoiceninja"
invoiceninja_traefik_network: "traefik-net"
invoiceninja_traefik_certresolver: ""
invoiceninja_traefik_entrypoints: "websecure"
invoiceninja_domain: "invoiceninja.mini.debrutal.dev"
invoiceninja_app_url: "https://{{ invoiceninja_domain }}"
invoiceninja_db_name: "ninja"
invoiceninja_db_user: "ninja"
invoiceninja_db_password: "changeme"
invoiceninja_db_root_password: "changeme_root"
invoiceninja_app_key: ""
invoiceninja_admin_user: "{{ vault_invoiceninja_admin_user | default(default_admin_username | default('debrutal')) }}"
invoiceninja_admin_email: "{{ vault_invoiceninja_admin_email | default(default_admin_email | default('duennes@gmail.com')) }}"
invoiceninja_admin_password: "{{ vault_invoiceninja_admin_password | default(default_admin_password | default('')) }}"
