---
- name: Restart systemd-journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
  when: ansible_connection != 'docker' and (ansible_facts['virtualization_type'] | default('')) != 'docker'
