---
homepage_version: "v2.4.0"
homepage_dir: "/opt/homepage"
homepage_traefik_network: "traefik-net"
homepage_traefik_certresolver: ""
homepage_traefik_entrypoints: "websecure"
homepage_domain: "dash.mini.debrutal.dev"
homepage_site_url: "https://{{ homepage_domain }}"
homepage_allowed_hosts: "{{ [
  homepage_domain,
  homepage_domain ~ ':443',
  homepage_domain ~ ':80',
  'homepage',
  'homepage:3000',
  'dashboard.mini.debrutal.dev',
  'dashboard.mini.debrutal.dev:443',
  'dashboard.mini.debrutal.dev:80',
  'localhost',
  '127.0.0.1'
] | join(',') }}"
homepage_uptime_kuma_url: "http://uptime-kuma:3001"
homepage_uptime_kuma_slug: "{{ uptime_kuma_status_slug | default('default') }}"
homepage_home_assistant_url: "http://homeassistant.local:8123"
lago_front_url: "https://lago.mini.debrutal.dev"  # noqa: var-naming[no-role-prefix]
bookorbit_site_url: "https://bookorbit.mini.debrutal.dev"  # noqa: var-naming[no-role-prefix]
agentzero_site_url: "https://agentzero.mini.debrutal.dev"  # noqa: var-naming[no-role-prefix]
pinchflat_site_url: "https://pinchflat.mini.debrutal.dev"  # noqa: var-naming[no-role-prefix]
ebook2audiobook_site_url: "https://ebook2audiobook.mini.debrutal.dev"  # noqa: var-naming[no-role-prefix]
