---
espocrm_version: "10.0.8"
espocrm_dir: "/opt/espocrm"
espocrm_traefik_network: "traefik-net"
espocrm_traefik_certresolver: ""
espocrm_traefik_entrypoints: "websecure"
espocrm_domain: "espocrm.mini.debrutal.dev"
espocrm_domain_alias: "epsocrm.mini.debrutal.dev"
espocrm_site_url: "https://{{ espocrm_domain }}"
espocrm_db_name: "espocrm"
espocrm_db_user: "espocrm"
espocrm_db_password: "changeme"
espocrm_db_root_password: "changeme_root"
espocrm_admin_username: "{{ vault_espocrm_admin_username | default(default_admin_username | default('debrutal')) }}"
espocrm_admin_password: "{{ vault_espocrm_admin_password | default(default_admin_password | default('')) }}"
espocrm_admin_email: "{{ vault_espocrm_admin_email | default(default_admin_email | default('duennes@gmail.com')) }}"
