---
- name: Restart podman socket
  ansible.builtin.systemd:
    name: podman.socket
    state: restarted
  when: ansible_connection != 'docker' and (ansible_facts['virtualization_type'] | default('')) != 'docker'

- name: Restart podman service
  ansible.builtin.systemd:
    name: podman.service
    state: restarted
  when: ansible_connection != 'docker' and (ansible_facts['virtualization_type'] | default('')) != 'docker'
